#ifndef ZINNIA_SYSCALL_NUMBERS_H
#define ZINNIA_SYSCALL_NUMBERS_H

enum {
    ZN_SYSCALL_PANIC,

    ZN_SYSCALL_LOG,

    ZN_SYSCALL_ARCHCTL,

    ZN_SYSCALL_HANDLE_VALIDATE,
    ZN_SYSCALL_HANDLE_DROP,
    ZN_SYSCALL_HANDLE_CLONE,

    ZN_SYSCALL_MEM_ALLOC,
    ZN_SYSCALL_MEM_FREE,

    ZN_SYSCALL_CHANNEL_CREATE,
    ZN_SYSCALL_CHANNEL_OPEN,
    ZN_SYSCALL_CHANNEL_READ,
    ZN_SYSCALL_CHANNEL_WRITE,

    ZN_SYSCALL_THREAD_CREATE,
    ZN_SYSCALL_THREAD_DESTROY,
};

#endif
